//测试数据
angular.services

  .factory('testData', function () {
    var dishList = [
      {
        id:1,
        name:'北京烤鸭',
        total:8,
        picture:'./img/beijingkaoya.jpg',
        introduce:'用料为优质肉食鸭北京鸭，果木炭火烤制，色泽红润，肉质肥而不腻，外脆里嫩。',
        cook:'张三',
        price:99.00,
        discount:89.00
      },
      {
        id:2,
        name:'糖醋排骨',
        total:10,
        picture:'./img/tangcupaigu.jpg',
        introduce:'糖醋排骨(Sweet and Sour Spare Ribs)是糖醋味型中具有代表性的一道大众喜爱的汉族传统名菜，它选用新鲜猪子排' +
        '作料，肉质鲜嫩，成莱色泽红亮油润',
        cook:'张三',
        price:45.00,
        discount:39.00
      },
      {
        id:3,
        name:'剁椒鱼头',
        total:4,
        picture:'./img/duojiaoyutou.jpg',
        introduce:'剁椒鱼头是湖南湘潭以及湘赣交界地方的一道汉族传统名菜，属湘菜系。',
        cook:'李四',
        price:40.00,
        discount:35.00
      },
      {
        id:4,
        name:'龙井虾仁',
        total:3,
        picture:'./img/longjingxiaren.jpg',
        introduce:'龙井虾仁，是配以龙井茶的嫩芽烹制而成的虾仁，是富有浙江杭州地方特色的汉族名菜。',
        cook:'李四',
        price:99.00,
        discount:89.00
      }
    ];

    var dishDetail = {
      1:{
        id:1,
        name:'北京烤鸭',
        total:5,
        picture:'./img/beijingkaoya.jpg',
        introduce:'用料为优质肉食鸭北京鸭，果木炭火烤制，色泽红润，肉质肥而不腻，外脆里嫩。',
        ingredients:'光鸭、葱段、甜面酱、薄饼、青瓜',
        feature:'它以色泽红艳，肉质细嫩，味道醇厚，肥而不腻的特色，被誉为“天下美味”',
        cook:'张三',
        price:99.00,
        discount:89.00,
        good:22,
        medium:0,
        sad:0,
        comment:[
          {
            name:'老张',
            text:'很美味，赞赞赞',
            type:1,
            date:1446949373246
          },
          {
            name:'老赵',
            text:'很好，很好，很好，很好，很好，很好，天下第一美味',
            type:1,
            date:1446949373246
          },
          {
            name:'老钱',
            text:'还不错',
            type:1,
            date:1446949313246
          },
          {
            name:'老孙',
            text:'很美味，给好评',
            type:1,
            date:1446949373246
          },
          {
            name:'老张',
            text:'很美味，就好',
            type:1,
            date:1446949313246
          },
          {
            name:'老张',
            text:'很美味，就好！！！！！！',
            type:1,
            date:1446949313246
          },
          {
            name:'老赵',
            text:'好吃不上火',
            type:1,
            date:1446949313246
          },
          {
            name:'老钱',
            text:'难忘滴味道',
            type:1,
            date:1446949313246
          },
          {
            name:'老孙',
            text:'很美味，难忘滴味道',
            type:1,
            date:1446949313246
          },
          {
            name:'老张',
            text:'很美味，赞赞赞',
            type:1,
          },
          {
            name:'老张',
            text:'好吃不上火，赞赞赞',
            type:1,
            date:1446949313246
          },
          {
            name:'老赵',
            text:'天下第一美味',
            type:1,
            date:1446949313246
          },
          {
            name:'老钱',
            text:'还不错',
            type:1,
            date:1446949313246
          },
          {
            name:'老孙',
            text:'很好好，很好，给好评',
            type:1,
            date:1446949313246
          },
          {
            name:'老张',
            text:'很美味，赞赞赞',
            type:1,
            date:1446949313246
          },
          {
            name:'老张',
            text:'很美味，赞赞赞',
            type:1,
            date:1446949313246
          },
          {
            name:'老赵',
            text:'很好，很好，很好天下第一美味',
            type:1,
            date:1446949313246
          },
          {
            name:'老钱',
            text:'还不错',
            type:1,
            date:1446949313246
          },
          {
            name:'老孙',
            text:'很美味，给好评',
            type:1,
            date:1446949313246
          },
          {
            name:'老张',
            text:'很美味，赞赞赞',
            type:1,
            date:1446949313246
          },
          {
            name:'老张',
            text:'很美味，赞赞赞',
            type:1,
            date:1446949313246
          },
          {
            name:'老赵',
            text:'很好，很好，很好，很好，很好，很好，天下第一美味',
            type:1,
            date:1446949313246
          },
          {
            name:'老钱',
            text:'还不错',
            type:1,
            date:1446949313246
          },
          {
            name:'老孙',
            text:'很美味，给好评',
            type:1,
            date:1446949313246
          },
          {
            name:'老张',
            text:'很美味，赞赞赞',
            type:1,
            date:1446949313246
          }
        ]
      },
      2:{
        id:2,
        name:'糖醋排骨',
        total:10,
        picture:'./img/tangcupaigu.jpg',
        introduce:'糖醋排骨(Sweet and Sour Spare Ribs)是糖醋味型中具有代表性的一道大众喜爱的汉族传统名菜',
        ingredients:'猪小排',
        feature:'它选用新鲜猪子排作料，肉质鲜嫩，成莱色泽红亮油润',
        cook:'张三',
        price:45.00,
        discount:39.00,
        good:5,
        medium:0,
        sad:0,
        comment:[
          {
            name:'老张',
            text:'很美味，赞赞赞',
            type:1,
            date:1446949313246
          },
          {
            name:'老赵',
            text:'很好，很好，很好，很好，很好，很好，天下第一美味',
            type:1,
            date:1446949313246
          },
          {
            name:'老钱',
            text:'还不错',
            type:1,
            date:1446949313246
          },
          {
            name:'老孙',
            text:'很美味，给好评',
            type:1,
            date:1446949313246
          },
          {
            name:'老张',
            text:'很美味，赞赞赞',
            type:1,
            date:1446949313246
          }
        ]
      },
      3:{
        id:3,
        name:'剁椒鱼头',
        total:4,
        picture:'./img/duojiaoyutou.jpg',
        introduce:'剁椒鱼头[1]  是湖南湘潭以及湘赣交界地方的一道汉族传统名菜，属湘菜系。',
        ingredients:'胖头鱼头、香葱、姜片、剁椒、盐、料酒、植物油、香油',
        feature:'以剁辣椒的“咸”和“辣”沁入鱼头风味独具一格。菜品色泽红亮、味浓、肉质细嫩。肥而不腻、口感软糯、鲜辣适口',
        cook:'李四',
        price:40.00,
        discount:35.00,
        good:5,
        medium:0,
        sad:0,
        comment:[
          {
            name:'老张',
            text:'很美味，赞赞赞',
            type:1,
            date:1446949313246
          },
          {
            name:'老赵',
            text:'很好，很好，很好，很好，很好，很好，天下第一美味',
            type:1,
            date:1446949313246
          },
          {
            name:'老钱',
            text:'还不错',
            type:1,
            date:1446949313246
          },
          {
            name:'老孙',
            text:'很美味，给好评',
            type:1,
            date:1446949313246
          },
          {
            name:'老张',
            text:'很美味，赞赞赞',
            type:1,
            date:1446949313246
          }
        ]
      },
      4:{
        id:4,
        name:'龙井虾仁',
        total:3,
        picture:'./img/longjingxiaren.jpg',
        introduce:'龙井虾仁，是配以龙井茶的嫩芽烹制而成的虾仁，是富有浙江杭州地方特色的汉族名菜。',
        ingredients:'活大河虾，龙井新茶，鸡蛋，绍酒，精盐。味精，淀粉，熟猪油',
        feature:'选用“色绿、香郁、味甘、形美”的明前龙井新茶和鲜河虾仁烹制而成。成菜虾仁白玉鲜嫩，茶叶碧绿清香，色泽雅致，滋味独特',
        cook:'李四',
        price:99.00,
        discount:89.00,
        good:5,
        medium:0,
        sad:0,
        comment:[
          {
            name:'老张',
            text:'很美味，赞赞赞',
            type:1,
            date:1446949313246
          },
          {
            name:'老赵',
            text:'很好，很好，很好，很好，很好，很好，天下第一美味',
            type:1,
            date:1446949313246
          },
          {
            name:'老钱',
            text:'还不错',
            type:1,
            date:1446949313246
          },
          {
            name:'老孙',
            text:'很美味，给好评',
            type:1,
            date:1446949313246
          },
          {
            name:'老张',
            text:'很美味，赞赞赞',
            type:1,
            date:1446949313246
          }
        ]
      }
    }
    return {
      dishList:dishList,
      dishDetail:dishDetail
    }
  }
);
